### ISSUE TITLE
Mount for Action Cam

### ISSUE THREAD

**Issue by linsenpago** [RubberQuads/TPU-parts#1]
Hi! 

I was wondering if you also would have a mount for an action cam available?
I would like to mount a Caddx Peanut on the Squirrel from time to time... ;-)

BR
Alex

**Comment by RubberQuads** [comment]
Is the body the same size as the insta360go2?
(I have a mount for that one)

**Comment by linsenpago** [comment]
It is nearly the same size... maybe i have to print it 1% lager than for the go2... because in the go2 cases i print so far it was very hard to put the camera in - but it was possible

**Comment by linsenpago** [comment]
please, would you like to share it with us?

**Comment by RubberQuads** [comment]
Finally I found the mount on an old harddrive!
Sorry for taking that long to get this into the repo.
https://github.com/RubberQuads/TPU-parts/blob/b78c4b34845b353cf590397e670887dfedc8e65c/Squirrel/Insta360_go2_mount.stl

**Comment by RubberQuads** [comment]
Hope that solves the issue ;-)

**Comment by linsenpago** [comment]
great! Thank you very much!
